-- Get all pairs of actors that worked together.
SELECT A1.ACTOR_ID AS FIRST_ACTOR, A2.ACTOR_ID AS SECOND_ACTOR, A1.FILM_ID
FROM SAKILA.FILM_ACTOR A1
LEFT JOIN SAKILA.FILM_ACTOR A2 
ON A1.FILM_ID = A2.FILM_ID
AND A1.ACTOR_ID <> A2.ACTOR_ID;

-- Get all pairs of customers that have rented the same film more than 3 times.
SELECT * 
FROM SAKILA.RENTAL;

SELECT R1.CUSTOMER_ID AS CUSTOMER_1, R2.CUSTOMER_ID AS CUSTOMER_2, COUNT(*) AS RENTED
FROM SAKILA.RENTAL R1
JOIN SAKILA.RENTAL R2 
ON R1.INVENTORY_ID = R2.INVENTORY_ID
AND R1.CUSTOMER_ID <> R2.CUSTOMER_ID
GROUP BY 1, 2 
HAVING COUNT(*) > 3;

-- Get all possible pairs of actors and films.
SELECT FA.ACTOR_ID, F.FILM_ID, F.TITLE
FROM SAKILA.FILM_ACTOR FA
LEFT JOIN SAKILA.FILM F
ON FA.FILM_ID = F.FILM_ID
ORDER BY 1,2;